Refactor for Hypercore 10
RangerMauve/hyper-flood pull request #1
Opened 2022-07-24 03:19 UTC by OzymandiasTheGreat

As promised, here's a PR :smiley: 

The problem with Hypercore 10 is that it does not accept a function as `registerExtension` argument. This also means there's no way to get the Extension object from handlers.

So I changed up how `extension()` works. Now it takes `(extension (name), feed)` as args,
and then it just `this._ext = feed.registerExtension(extension, {...})`

Hope you find this an acceptable change.

Otherwise, it works perfectly, kudos.

2022-08-30 16:00 UTC, RangerMauve requested changes
Mind formatting the code through the [standard.js](https://standardjs.com/) module? The diff is a bit hard to read with all the formatting changes.

2022-08-30 16:16 UTC, OzymandiasTheGreat commented
I'm so sorry :sweat_smile: I didn't notice the formatter. I'll fix that ASAP

2022-08-30 18:38 UTC, RangerMauve requested changes
TY for looking into this. 😁

Looking good, just not sure whether this could still work with replication stream extensions (or if that's still even a thing).

Also, mind deleting the `yarn.lock` and adding it to the gitignore? It's kind of overkill for a small library like this.

2022-08-30 18:38 UTC, RangerMauve commented on index.js
> -    const sendMethod = this._ext.broadcast ? 'broadcast' : 'send'
This was here to enable supporting replication protocol level extensions as well as individual hypercore extensions. Mind making sure that that would still work?

2022-08-30 18:38 UTC, RangerMauve commented on package.json
> +	"name": "hyper-flood",
Mind also reformatting the package.json to use two spaces? I prefer tabs usually, but the NPM formatter defaults to spaces and this can cause unnecessary diffs down the line

2022-10-08 05:30 UTC, OzymandiasTheGreat commented on index.js
> -    const sendMethod = this._ext.broadcast ? 'broadcast' : 'send'
I just reverted this change, not sure if relevant still with the changes to hypercore, but better safe

2022-10-08 05:30 UTC, OzymandiasTheGreat commented on package.json
> +	"name": "hyper-flood",
Done

2022-10-08 05:31 UTC, OzymandiasTheGreat commented
Sorry it took so long, first month at the new job, things a bit hectic for me

2023-01-10 21:30 UTC, RangerMauve commented
Does this still make sense with the latest holepunch changes?

2023-01-11 15:12 UTC, OzymandiasTheGreat commented
Honestly, no clue. I'll have to look into it, prob over the weekend.

2023-01-17 04:02 UTC, OzymandiasTheGreat commented
So I finally got the time to play around with hypercores again, and honestly I don't know.
Hypercore still has extension support and this PR makes hyper-flood compatible with current implementation.
The thing that trips me up is Protomux. Going forward the stance is to use that instead of extensions and after some testing protomux makes the whole concept of flooding passé 😆 
When replicating hypercores/corestores you no longer need to be replicating the same hypercore/know the public key, protomux messages propagate through entire swarm regardless.
All the deduplication and forwarding happens automatically and efficiently, so it kinda deprecates this module entirely.

2023-11-17 04:43 UTC, closed without merging